debug

diff --git a/.github/workflows/bump.yml b/.github/workflows/bump.yml
--- a/.github/workflows/bump.yml
+++ b/.github/workflows/bump.yml
@@ -23,20 +23,46 @@ jobs:
           echo "current_version=$current_version" >> $GITHUB_ENV
           # a=(${current_version//./ })
           IFS='.' read -ra a <<< "$current_version"
+          echo "Before incrementing: ${a[@]}"
 
-          echo "Current version: $current_version"
-          echo "Label: $label"
-          echo "Array values: ${a[@]}"
-          
           if [ "$label" = "major" ]; then
-              ((a[0]++))
+              if [[ ${a[0]} =~ ^[0-9]+$ ]]; then
+                  ((a[0]++))
+              else
+                  echo "Error: a[0] is not a number"
+                  exit 1
+              fi
           elif [ "$label" = "minor" ]; then
-              ((a[1]++))
+              if [[ ${a[1]} =~ ^[0-9]+$ ]]; then
+                  ((a[1]++))
+              else
+                  echo "Error: a[1] is not a number"
+                  exit 1
+              fi
           elif [ "$label" = "patch" ]; then
-              ((a[2]++))
+              if [[ ${a[2]} =~ ^[0-9]+$ ]]; then
+                  ((a[2]++))
+              else
+                  echo "Error: a[2] is not a number"
+                  exit 1
+              fi
           fi
-          new_version="${a[0]}.${a[1]}.${a[2]}"
-          echo "new_version=$new_version" >> $GITHUB_ENV
+          
+          echo "After incrementing: ${a[@]}"
+          
+          # echo "Current version: $current_version"
+          # echo "Label: $label"
+          # echo "Array values: ${a[@]}"
+          
+          # if [ "$label" = "major" ]; then
+          #     ((a[0]++))
+          # elif [ "$label" = "minor" ]; then
+          #     ((a[1]++))
+          # elif [ "$label" = "patch" ]; then
+          #     ((a[2]++))
+          # fi
+          # new_version="${a[0]}.${a[1]}.${a[2]}"
+          # echo "new_version=$new_version" >> $GITHUB_ENV
 
       # - name: Commit and push if it has changed
       #   run: |
